name: Main Workflow

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]     # Publish semver tags as releases.
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: read
  id-token: write
  security-events: write

jobs:
  workflow:
    uses: tychodev321/workflow-templates/.github/workflows/container-publish.yml@main
